### ISSUE TITLE
Support other webhooks

### ISSUE THREAD

**Issue by Suleman-Elahi** [rowyio/feedbackfin#3]
Failed to setup Rowy so I tried webhook.site instead. Now, when I send feedback, it fails. A request is made to the webhook, but with no data.

![image](https://user-images.githubusercontent.com/24384996/163660297-a1e74a61-b9a9-486f-8b32-39370f78e380.png)

![image](https://user-images.githubusercontent.com/24384996/163660305-ffb92b27-f92a-4e10-b1a3-ae9e6afc4fb3.png)

**Comment by notsidney** [comment]
Hi @Suleman-Elahi, the error produced by sending to Webhook.site is a CORS issue, as seen in the console:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/27017118/163673268-8e87bac0-f999-4b65-bdda-7e302165feb8.png">

This can be fixed by ticking “Cors Headers” in Webhook.site.

<img width="116" alt="image" src="https://user-images.githubusercontent.com/27017118/163673296-eb1d3c93-642d-4a53-82c6-028264edc523.png">

Otherwise, we’d love to help you set up Rowy and troubleshoot the issues you had via our Discord: https://discord.gg/fjBugmvzZP
